=head1 TSC Standard Scripting Library API documentation

This documentation covers TSC’s standard scripting library (SSL), a
set of ruby files that comes together with TSC. These library files
build upon the core functionalities provided by the TSC
scripting core API and extend it to be more easy to
use. As explained, the SSL is written entirely in Ruby. Its
implementation can be found inside the F<data/scripting/> folder
of an TSC installation.

=head2 Usage

The libraries from the SSL are loaded automatically in alphabetical order.
TSC prints a message to the console each time it loads an SSL file, which
might be useful for debugging the SSL itself.

All modules in the SSL reside under the C<Std> module, so that e.g.
the C<Switch> class has to be accessed as C<Std::Switch>. Alternatively,
it is possible to include the C<Std> namespace with C<#include>.

For the usage of each component of the SSL, refer to its respective
documentation.

=head2 Contributing

The SSL is quite small right now. The TSC team encourages every level
scripter to submit code snippets he uses frequently in his/her levels
to the mailing list or bug tracker, so that they can be considered for
addition to the SSL in a future version of TSC.

=head2 List of SSL classes and modules

=cut
